import "./globals.css";
import { cx } from "cva";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={cx(inter.className)}>
        <div className="container">
          <p className="text-solid h-nav">DOCS. I should be solid</p>
        </div>
        {children}
      </body>
    </html>
  );
}
